// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NewsManagementSystem.DAL.Entities;

[Table("Category")]
[Index("CategoryName", Name = "UQ__Category__8517B2E0248B686B", IsUnique = true)]
public partial class Category
{
    [Key]
    public int CategoryID { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string CategoryName { get; set; }

    [Column(TypeName = "text")]
    public string CategoryDescription { get; set; }

    public int? ParentCategoryID { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("ParentCategory")]
    public virtual ICollection<Category> InverseParentCategory { get; set; } = new List<Category>();

    [InverseProperty("Category")]
    public virtual ICollection<NewsArticle> NewsArticles { get; set; } = new List<NewsArticle>();

    [ForeignKey("ParentCategoryID")]
    [InverseProperty("InverseParentCategory")]
    public virtual Category ParentCategory { get; set; }
}