// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NewsManagementSystem.DAL.Entities;

[Table("Category")]
public partial class Category
{
    [Key]
    public short CategoryID { get; set; }

    [Required]
    [StringLength(100)]
    public string CategoryName { get; set; }

    [Required]
    [StringLength(250)]
    public string CategoryDesciption { get; set; }

    public short? ParentCategoryID { get; set; }

    public bool? IsActive { get; set; }

    [InverseProperty("ParentCategory")]
    public virtual ICollection<Category> InverseParentCategory { get; set; } = new List<Category>();

    [InverseProperty("Category")]
    public virtual ICollection<NewsArticle> NewsArticles { get; set; } = new List<NewsArticle>();

    [ForeignKey("ParentCategoryID")]
    [InverseProperty("InverseParentCategory")]
    public virtual Category ParentCategory { get; set; }
}