// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NewsManagementSystem.DAL.Entities;

[Table("NewsArticle")]
public partial class NewsArticle
{
    [Key]
    public int NewsArticleID { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string NewsTitle { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Headline { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string NewsContent { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string NewsSource { get; set; }

    public int CategoryID { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string NewsStatus { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string CreatedByID { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string UpdatedByID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ModifiedDate { get; set; }

    [ForeignKey("CategoryID")]
    [InverseProperty("NewsArticles")]
    public virtual Category Category { get; set; }

    [ForeignKey("CreatedByID")]
    [InverseProperty("NewsArticleCreatedBies")]
    public virtual SystemAccount CreatedBy { get; set; }

    [ForeignKey("UpdatedByID")]
    [InverseProperty("NewsArticleUpdatedBies")]
    public virtual SystemAccount UpdatedBy { get; set; }

    [ForeignKey("NewsArticleID")]
    [InverseProperty("NewsArticles")]
    public virtual ICollection<Tag> Tags { get; set; } = new List<Tag>();
}