// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NewsManagementSystem.DAL.Entities;

[Table("SystemAccount")]
[Index("AccountName", Name = "UQ__SystemAc__406E0D2E350E5316", IsUnique = true)]
[Index("AccountEmail", Name = "UQ__SystemAc__FC770D339E2F8AF7", IsUnique = true)]
public partial class SystemAccount
{
    [Key]
    [StringLength(100)]
    [Unicode(false)]
    public string AccountID { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string AccountName { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string AccountEmail { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string AccountRole { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string AccountPassword { get; set; }

    [InverseProperty("CreatedBy")]
    public virtual ICollection<NewsArticle> NewsArticleCreatedBies { get; set; } = new List<NewsArticle>();

    [InverseProperty("UpdatedBy")]
    public virtual ICollection<NewsArticle> NewsArticleUpdatedBies { get; set; } = new List<NewsArticle>();
}