// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NewsManagementSystem.DAL.Entities;

[Table("Tag")]
public partial class Tag
{
    [Key]
    public int TagID { get; set; }

    [StringLength(50)]
    public string TagName { get; set; }

    [StringLength(400)]
    public string Note { get; set; }

    [ForeignKey("TagID")]
    [InverseProperty("Tags")]
    public virtual ICollection<NewsArticle> NewsArticles { get; set; } = new List<NewsArticle>();
}