// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NewsManagementSystem.DAL.Entities;

[Table("Tag")]
[Index("TagName", Name = "UQ__Tag__BDE0FD1D2710FCC2", IsUnique = true)]
public partial class Tag
{
    [Key]
    public int TagID { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string TagName { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Note { get; set; }

    [ForeignKey("TagID")]
    [InverseProperty("Tags")]
    public virtual ICollection<NewsArticle> NewsArticles { get; set; } = new List<NewsArticle>();
}